version: "3.9"

services:
  # Serviço do banco de dados
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tarefasdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  # Serviço do backend (Node.js + Express)
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tarefasdb
      - DB_PORT=5432
    ports:
      - "3001:3001"
    networks:
      - app_network
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  # Serviço do frontend (React + Vite)
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - app_network
    depends_on:
      - backend

volumes:
  db_data:

#Rede personalizada para os serviços se comunicarem.
networks:
  app_network:
    driver: bridge
